# -*- coding: utf-8 -*-
"""decision tree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jqNEPH-23-5ocJnLJeS1rZA_yEsUgC0I
"""

import pandas as pd

df=pd.read_excel("/content/india_weather_rainfall_data.xlsx")

df.head()

df.info()

df.isnull().sum()

print("duplicate rows:",df.duplicated().sum())

print(df.columns.tolist())

df.info()

df.describe()

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print(df.isnull().sum())

df=df.dropna()

print("Duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)

high_rainfall=df[df["rainfall"]>50]
[["station_name","district","rainfall"]]

print(high_rainfall)

df.info()

df=df.dropna(subset=["rainfall"])

df=df[df["rainfall"]>=0]

rainy_days=df[df["rainfall"]>0]

heavy_rainfall=df[df["rainfall"]>50]

print("/nCleaneddata:")
print(df.head())

print("/nrainy_days:")
print(rainy_days.head())

print("/nheavy_rainfall:")
print(heavy_rainfall.head())

df.to_excel("cleaned_indian_rainfall.xlsx",index=False)

AP=df[df["state"] =="AP"]
print(AP.head())

highest_rainfall=df.sort_values(
    by="rainfall",
    ascending=False
)
print(highest_rainfall.head(10))

state_rainfall=df.groupby("state")["rainfall"].mean()
print(state_rainfall)

def classify_rainfall(x):
  if x<=2.4:
    return "Very Low"
  elif x<=15.5:
    return "Light"
  elif x<=64.4:
    return "Moderate"
  elif x<=115.5:
    return "heavy"
  else:
    return"Very High"

df["rainfall_category"]=df["rainfall"].apply(classify_rainfall)

print(df["rainfall_category"].value_counts())

print(df.describe())

import matplotlib.pyplot as plt

df["rainfall_category"].value_counts().plot(kind="bar")

plt.title("Rainfall Category Distribution")
plt.xlabel("Rainfall Category")
plt.ylabel("Number of Records")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

sns.heatmap(df.select_dtypes("number").corr(), annot=True)
plt.title("Correlation Heatmap")
plt.show()

plt.figure(figsize=(8,5))

sns.countplot(
    data=df,
    x="rainfall_category",
    order=["Very Low", "Light", "Moderate", "Heavy", "Very Heavy"]
)

plt.title("Rainfall Category Distribution")
plt.xlabel("Rainfall Category")
plt.ylabel("Number of Records")
plt.xticks(rotation=30)
plt.show()

plt.figure(figsize=(8,5))

sns.histplot(df["rainfall"], bins=30, kde=True)

plt.title("Distribution of Rainfall")
plt.xlabel("Rainfall (mm)")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(x=df["rainfall"])

plt.title("Rainfall Boxplot")
plt.xlabel("Rainfall (mm)")
plt.show()

plt.figure(figsize=(7,7))

df["rainfall_category"]=df["rainfall"].apply(classify_rainfall)

df["rainfall_category"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%"
)

plt.title("Rainfall Category Percentage")
plt.ylabel("")
plt.show()

df.columns

features = [
    "month",
    "avg_temp",
    "min_temp",
    "max_temp",
    "wind_speed",
    "air_pressure",
    "elevation",
    "latitude",
    "longitude"
]

X = df[features]
y = df["rainfall_category"]

print(X.head())
print(y.head())

print(X.isnull().sum())

numerical_features = [
    "avg_temp",
    "min_temp",
    "max_temp",
    "wind_speed",
    "air_pressure",
    "elevation",
    "latitude",
    "longitude"
]

for col in numerical_features:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print(df[numerical_features].dtypes)

for col in numerical_features:
    df[col] = df[col].fillna(df[col].median())

print(df[numerical_features].isnull().sum())

categorical_features = [
    "month",
    "season",
    "state",
    "district"
]

features = categorical_features + numerical_features

X = df[features]
y = df["rainfall_category"]

print("X shape:", X.shape)
print("y shape:", y.shape)

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        (
            "cat",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("encoder", OneHotEncoder(handle_unknown="ignore"))
            ]),
            categorical_features
        ),
        (
            "num",
            SimpleImputer(strategy="median"),
            numerical_features
        )
    ]
)

X = pd.get_dummies(
    X,
    columns=categorical_features,
    drop_first=True
)

print(X.dtypes.value_counts())

X = X.astype(float)

print(X.dtypes.value_counts())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training:", X_train.shape)
print("Testing:", X_test.shape)

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

dt_model = DecisionTreeClassifier(
    max_depth=10,
    random_state=42
)

dt_model.fit(X_train, y_train)

dt_pred = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_pred)

print("Decision Tree Accuracy:",
      dt_accuracy * 100, "%")

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

rf_accuracy = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy:",
      rf_accuracy * 100, "%")

import joblib

model_data = {
    "model": rf_model,
    "columns": X.columns.tolist(),
    "categorical_features": categorical_features
}

joblib.dump(model_data, "rainfall_model.pkl")

print("New rainfall_model.pkl created successfully")

from google.colab import files
files.download('rainfall_model.pkl')

print("Decision Tree Accuracy:", dt_accuracy * 100, "%")
print("Random Forest Accuracy:", rf_accuracy * 100, "%")

from sklearn.metrics import classification_report

print(classification_report(y_test, rf_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, rf_pred)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=rf_model.classes_,
    yticklabels=rf_model.classes_
)

plt.title("Rainfall Classification - Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.show()

results = pd.DataFrame({
    "Model": ["Decision Tree", "Random Forest"],
    "Accuracy": [
        dt_accuracy * 100,
        rf_accuracy * 100
    ]
})

print(results)

plt.figure(figsize=(7,5))

sns.barplot(
    data=results,
    x="Model",
    y="Accuracy"
)

plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy (%)")
plt.ylim(0, 100)

plt.show()

if rf_accuracy > dt_accuracy:
    best_model = rf_model
    best_pred = rf_pred
    best_name = "Random Forest"
else:
    best_model = dt_model
    best_pred = dt_pred
    best_name = "Decision Tree"

print("Best Model:", best_name)

import joblib

joblib.dump(
    best_model,
    "rainfall_classification_model.pkl"
)

print("Model saved successfully!")

import os

print(os.path.exists("rainfall_classification_model.pkl"))

new_data = pd.DataFrame({
    "month": ["July"],
    "season": ["Monsoon"],
    "state": ["Telangana"],
    "district": ["Hyderabad"],
    "avg_temp": [27],
    "min_temp": [23],
    "max_temp": [31],
    "wind_speed": [12],
    "air_pressure": [1005],
    "elevation": [500],
    "latitude": [17.38],
    "longitude": [78.48]
})

# Define the features lists again (as they were used for X_train)
categorical_features = [
    "month",
    "season",
    "state",
    "district"
]

numerical_features = [
    "avg_temp",
    "min_temp",
    "max_temp",
    "wind_speed",
    "air_pressure",
    "elevation",
    "latitude",
    "longitude"
]

# Ensure all numerical features are of type float (already handled by literal input for new_data)
for col in numerical_features:
    new_data[col] = pd.to_numeric(new_data[col], errors="coerce")

# Apply one-hot encoding to categorical features in new_data
new_data_processed = pd.get_dummies(
    new_data,
    columns=categorical_features,
    drop_first=True
)

# Convert all columns to float to match the training data
new_data_processed = new_data_processed.astype(float)

# Reindex new_data_processed to match the columns of X_train
# Fill any missing columns (i.e., categories not present in new_data but in X_train) with 0
# This is crucial for the model to work correctly
new_data_processed = new_data_processed.reindex(columns=X_train.columns, fill_value=0)

prediction = rf_model.predict(new_data_processed)

print("Predicted Rainfall Category:", prediction[0])

import joblib
joblib.dump(best_model, 'rainfall_model.pkl')

print("model saved")

joblib.dump(rf_model, 'rainfall_model.pkl')

from google.colab import files
files.download('rainfall_model.pkl')

